version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./base-datos/:/docker-entrypoint-initdb.d

  api_dev:
    build:
      context: .
      target: build
    depends_on:
      - db
    ports:
      - "8002:8001"
    command: sleep 3600
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
    volumes:
      - .:/app

  api:
    build: .
    depends_on:
      - db
    restart: on-failure:10
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password

volumes:
  db-data:
